spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/my_test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true